userInput store + getter on results page
fajnie-ze-wiesz/fzw-webapp pull request #55
Opened 2020-05-26 21:39 UTC by ppeczek

2020-05-31 17:34 UTC, apragacz requested changes
W aktualnej sytuacji widzę takie opcje dla tego PR: 
1. poprawić linijkę tylko tam gdzie jest XXX% tak jak pisałem w jednym z komentarzy i usunąć ten kod z nowym modułem VueX
2. zamknąć ten PR.

co do wyodrębniania store do osobnych modules to proponuję zrobić na to osobną dyskusję i później PR, jako że to jest mniej trywialna zmiana.

2020-05-31 17:34 UTC, apragacz commented on src/components/Results.vue
> +      userPrediction: 'getUserPrediction',
To nie zadziała jako że informacja o wynikach (`resultStats`) może być brana albo ze store albo wyciągana z URLa -w przypadku gdy ktoś kliknie w urla z wynikiem:
https://github.com/fajnie-ze-wiesz/fzw-webapp/blob/e6f2b047ed291c219e8987091466f0a39c7adf6b/src/components/Results.vue#L48-L57

Więc tak naprawdę wszystko powinno być brane stamtąd. Przechowujemy już taką informację w resultStats:
https://github.com/fajnie-ze-wiesz/fzw-webapp/blob/d8db8b2bc26b73e7d4a746c978b87bee0b0abd0a/src/data/result_stats.js#L11


 ale nie ma gettera który to wyciąga, i trzeba by go dopisać w tamtym miejscu (można go nazwać `getCorrectnessEstimate`) i użyć tutaj analogicznie jak jest to tutaj, np:
https://github.com/fajnie-ze-wiesz/fzw-webapp/blob/e6f2b047ed291c219e8987091466f0a39c7adf6b/src/components/Results.vue#L69-L78

Następnie `correctnessEstimate` użyć tam gdzie jest `XXX%` wyżej w kodzie.

2020-05-31 17:34 UTC, apragacz commented on src/store/modules/userInput.js
> +const state = {
Ten moduł VueX duplikuje aktualnie występujący stan w store:

https://github.com/fajnie-ze-wiesz/fzw-webapp/blob/d7fbb3a3f769f8567dd5c9c398e204994ead889e/src/store/index.js#L18-L19

Także widziałbym potencjalnie wyodrębnienia tych dwóch pól (`user` i `quizSetupInfo`) do osobnych modułów, natomiast myślę że lepiej zrobić to później (w kolejnym PR) i potencjalnie nawet post MVP jako że takie refactory mogą sporo namieszać przed wypuszczeniem MVP.

2020-06-04 01:14 UTC, fraunos approved these changes
Jestem za mergem, bo jest zadanko, które jest od tego zależne - pobieranie pytań wg kategorii

2020-06-04 09:02 UTC, apragacz commented
@fraunos 
Niestety, ale te zmiany nie zadziałają poprawnie (np. przy współdzielonym linku)

2021-05-28 21:19 UTC, closed without merging