Remove theme color meta tag
fajnie-ze-wiesz/fzw-webapp pull request #76
Opened 2020-06-25 22:42 UTC by apragacz

2020-06-26 06:26 UTC, fraunos commented
@apragacz a ten drugi tag co też ma taką wartość

https://github.com/fajnie-ze-wiesz/fzw-webapp/search?q=4DBA87&type=Code

2020-06-27 10:11 UTC, fraunos requested changes
chyba jest jeszcze jeden tag z taką wartością
https://github.com/fajnie-ze-wiesz/fzw-webapp/search?q=4DBA87&type=Code

2020-06-27 10:48 UTC, apragacz commented
> chyba jest jeszcze jeden tag z taką wartością
> https://github.com/fajnie-ze-wiesz/fzw-webapp/search?q=4DBA87&type=Code

@fraunos 
Z tego co widzę to ten metatag jest wykorzystywany tylko w safari i to w bardzo szczególnym przypadku:
https://developer.yoast.com/blog/safari-pinned-tab-icon-mask-icon/
ponadto odnosi się u nas do nieistniejącej już ikonki; więc go wywalę.

2020-06-27 11:46 UTC, apragacz commented
@fraunos 
Jednak zmieniłem zdanie - użyłem istniejącej ikony SVG i zmieniłem kolor na ten "Pomarańczowy" z naszej palety.
To działa tak że jak się przypnie taba to cała część loga podmieniana jest na podany kolor:
<img width="35" alt="Screenshot 2020-06-27 at 13 41 20" src="https://user-images.githubusercontent.com/168152/85921411-81b80e00-b87c-11ea-8cf2-5bc44f551d83.png">

2020-06-28 11:47 UTC, fraunos approved these changes

2020-06-28 22:25 UTC, merged